name: mylib

dependencies:
- base >= 4.7 && <= 5

ghc-options: -pgmL markdown-unlit

executables:
  Day01:
    main:                day01.lhs
    other-modules:       []
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - split
  Day02:
    main: day02.lhs
    other-modules: []
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  Day03:
    main: day03.lhs
    source-dirs: src
    dependencies:
    - split
    - containers
  Day04:
    main: day04.lhs
    source-dirs: src
    dependencies:
    - split
  Day05:
    main: day05.lhs
    source-dirs: src
    dependencies:
    - split
    - text